#!/bin/bash

# Copyright © 2024 slashOS Team and Contributors

# !WIP!

greet(){
  echo "Welcome to the slashOS Installer"
  echo "Due to obvious lack of skill, this installer currently lacks a gui :)"
  echo "Contribute here: https://github.com/slashOS-Team/installer"
  echo ""
  echo "++++++++++++++++"
  echo ""
  echo "DO NOT TURN OFF YOUR COMPUTER WHILE THE INSTALLER IS RUNNING"
}

informationasking(){
  read -p "Enter desired username: " name
  read -p "Enter desired password: " pass
  read -p "Enter desired root password: " rpass  
}
